---

- hosts: localhost
  gather_facts: no
  tasks:
    - name: test...
      local_action: cmop_vm
                    accessKey="MlpmZThvY3lMaXhvZjc1Mg=="
                    vpcCode="vpc-6QMjLFIS"
                    subnetCode="subnet-0ab8GPq3"
                    instanceTypeCode="InstanceType-hRlyzW77"
                    imageCode="Image-38jfGRl5"
                    numbers="3"
      register: vm_id

    - name: debug
      local_action: debug
                    msg="{{ vm_id }}"

